Andreas oversetter
koholition/zelda-links-awakening-NO pull request #12
Opened 2022-10-21 16:04 UTC by grenasberg

rettet litt i dialog 1 og begynt å oversette dialog 3. se gjennom og kommenter!

2022-10-21 17:17 UTC, tobiasvl commented on revisions/N0/src/text/dialog_3.asm
> +    db "hemmelighet!»@	 "
Synes utropstegnet skal være utenfor anførselstegnene, det er vel vanligere på norsk, mens på engelsk er de ofte inni (selv om de ikke er en del av sitatet/tittelen)

```suggestion
    db "hemmelighet»!@"
```

2022-10-21 17:17 UTC, tobiasvl commented on revisions/N0/src/text/dialog_3.asm
> +    db "modig mann.»    "
Samme her, bør ikke punktumet være utenfor?

```suggestion
    db "modig mann».    "
```

2022-10-21 17:17 UTC, tobiasvl commented on revisions/N0/src/text/dialog_3.asm
> +    db "  _…LEIRGAUK_… "
OBS, her er det bare 15 tegn på linja, så den vil ta med L fra neste linje! Kanskje ha mellomrom foran ordet også for symmetri?

```suggestion
    db " _… LEIRGAUK_…  "
```

2022-10-21 18:19 UTC, grenasberg commented on revisions/N0/src/text/dialog_3.asm
> +    db "hemmelighet!»@	 "
ja, det ser bedre ut

2022-10-21 18:21 UTC, grenasberg commented on revisions/N0/src/text/dialog_3.asm
> +    db "  _…LEIRGAUK_… "
mellomrommet foran ordet blir vel en smule større enn mellomrommet i "_…"-trikset. men det er kanskje så lite forskjell at det ikke gjør noe.

2022-10-21 22:33 UTC, juliusvl commented on revisions/N0/src/text/dialog_3.asm
> +    db "    Ja  Nei<ask>"
På engelsk er det store bokstaver i svarene, er det noen grunn til at det er endra i den norske?

2022-10-21 22:36 UTC, juliusvl commented on revisions/N0/src/text/dialog_3.asm
> +    db "  _…LEIRGAUK_… "
e9

2022-10-22 19:15 UTC, grenasberg commented on revisions/N0/src/text/dialog_3.asm
> +    db "    Ja  Nei<ask>"
Mest fordi jeg ikke aner hvorfor det er stort på den engelske? kikket på den tyske oversettelsen, og der var det skrevet på vanlig måte.

2022-10-22 19:17 UTC, grenasberg commented on revisions/N0/src/text/dialog_3.asm
> +    db "    Ja  Nei<ask>"
Er det liksom at han skriker svaret?

2022-10-23 08:56 UTC, juliusvl commented on revisions/N0/src/text/dialog_3.asm
> +    db "    Ja  Nei<ask>"
Aner ikke. Må jo være en grunn? Eller kanskje det er ulike folk som har oversatt, og så har det vært usikkerhet rundt standard prosedyre? Hvem veit

2022-10-23 08:59 UTC, juliusvl commented on revisions/N0/src/text/dialog_3.asm
> +    db "sikk fører til_…@"
leads, ikke leads to? Husker ikke helt kontekst her, men foreslår «Leirgaukens musikk fører…» eller «leder…» så det blir likere.

2023-03-25 15:35 UTC, tobiasvl requested changes

2023-03-25 15:35 UTC, tobiasvl commented on revisions/N0/src/text/dialog_3.asm
> +    db "  _…LEIRGAUK_… "
Jeg tenker det går bra, blir mer symmetrisk det enn ikke noe mellomrom foran. Og sånn her blir det på en måte halvannet mellomrom foran den første ellipsen og to etter den siste ellipsen, så alt balanserer hverandre ut liksom

2023-03-25 15:35 UTC, tobiasvl commented on revisions/N0/src/text/dialog_3.asm
> +    db "sikk fører til_…@"
```suggestion
    db "musikk fører_…@"
```

2023-03-25 15:35 UTC, tobiasvl commented on revisions/N0/src/text/dialog_3.asm
> +    db "Leirgaukens mu-"
```suggestion
    db "Leirgaukens    "
```

2023-03-25 15:36 UTC, tobiasvl approved these changes

2023-03-25 15:36 UTC, merged