Julius oversettelse3
koholition/zelda-links-awakening-NO pull request #13
Opened 2022-10-21 19:51 UTC by juliusvl

Gjorde forsøk på å oversette en hel del, dialog2.asm

2022-10-21 21:06 UTC, tobiasvl requested changes

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "våkner! Som     "
Foreslår å droppe ellipse etter «meg» så det ikke blir så mye tomrom
```suggestion
    db "våkner! Som meg "
```

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "meg_… er_… du_… "
```suggestion
    db "er_… du_… i…_   "
```

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "i_… drømmen_…   "
```suggestion
    db "drømmen_… hans…_@"
```

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "hans_…@"
```suggestion
```

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "PYTT! Jeg kommer"
```suggestion
    db "PØH! Jeg kommer "
```

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "ikke til å holde"
Litt usikker på «å holde tilbake». Er det idiomatisk norsk?

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "Halehula. Hent  "
Føler ikke at «hent» er naturlig i denne konteksten. Kanskje bare «finn»?
```suggestion
    db "Halehula. Finn  "
```

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "to templer, det "
Her burde det vel egentlig være semikolon hehehe

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "nesten framme.  "
Dette minner meg om at fotografen sa «fremkalle» i #12. De er jo forskjellige karakterer, så det trenger ikke være det samme, men kanskje det ville vært mer naturlig om Ugla sa «fremme» i hvert fall?

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "veier har       "
Mye tomrom på høyre side her, foreslår å fjerne «har» og komprimere litt.
```suggestion
    db "veier krysset   "
```

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "krysset hver-   "
Fortsettelse fra over. Da slipper vi også å dele «hverandre».
```suggestion
    db "hverandre, gutt."
```

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "andre, gutt. Du "
```suggestion
```

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "må dykke ned i  "
```suggestion
    db "Du må dykke ned "
```

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "vannet i Martas "
Kanskje også fjerne «vannet» for å få det til å flyte bedre.
```suggestion
    db "i Martas bukt   "
```

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "bukt for å komme"
```suggestion
    db "for å komme til "
```

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "til Mallegapet_…"
```suggestion
    db "Mallegapet_…    "
```

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "     SOVET_…    "
```suggestion
    db "    SLUMRET_…   "
```
Kanskje?

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "  DYR, EN HEL   "
Skal vi prøve oss på et semikolon her da? Hvis noen skal ha semikolon må det være Vindfisken!
```suggestion
    db "  DYR; EN HEL   "
```

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
>      db "... ... ... ... "
Wow, ekte punktum

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "  DRØMMER TAR   "
Føler dette blir litt casual? Vet ikke om «DET LIGGER I DRØMMERS NATUR AT DE EN GANG MÅ TA SLUTT» funker, det er veldig langt i hvert fall, men kanskje «ALLE DRØMMER MÅ TA SLUTT» eller noe?

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "ÉN DAG HUSKER DU"
Vindfisken sier «thou», så egentlig tenkte jeg at han skulle si «De», men tror egentlig ikke det funker så bra når alt er store bokstaver. Så egentlig tror jeg dette er bra!

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "kommer bare i   "
Litt unaturlig med «kommer» her? På engelsk er det «present continuous tense», men det brukes lite på norsk. Foreslår noe så enkelt som:
```suggestion
    db "er bare i veien!@"
```

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "veien!@"
```suggestion
```

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "_… Tusen takk!  "
```suggestion
    db "_… Takk for det!"
```

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "He! Er du klar?!"
```suggestion
    db "he! Er du klar?!"
```

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "piler! Heh Heh! "
Foreslår å flytte (og fornorske) «He He He» fra bombedialogen hit, siden «Heh Heh» ikke er så norsk
```suggestion
    db "piler! Hehehe!  "
```

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
>      db "Heh Heh Heh!    "
```suggestion
    db "He he he he!    "
```

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "BRUDNE, DU SKAL "
Hmm, vet ikke hva jeg synes om at «SHOULD» blir til «SKAL». Kanskje «BØR»?

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "Hæ? Tablå?@"
Haha. Ser for meg Ea som leser dette og tenker det samme, men fordi hun ikke aner hva et tablå er

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "Heh heh! Du vil "
```suggestion
    db "Hehehe! Du vil  "
```

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "rundt på! Hah!  "
```suggestion
    db "rundt på! Haha! "
```

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "til å sove      "
```suggestion
    db "til å sove til  "
```

2022-10-21 21:06 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "uendelig! Hvis  "
```suggestion
    db "evig tid! Hvis  "
```

2022-10-21 22:01 UTC, juliusvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "ikke til å holde"
Jeg var også i tvil her, men fant ikke på noe bedre. Å «holde tilbake» i gammeldags krig liksom, men det er kanskje egentlig en teit norsk versjon av engelsk uttrykk?

2022-10-21 22:05 UTC, juliusvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "Hæ? Tablå?@"
vet hun hva en illusjon er da? hehe

2022-10-21 22:13 UTC, juliusvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "nesten framme.  "
enig

2022-10-21 22:15 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "Hæ? Tablå?@"
neppe!

2022-10-21 22:20 UTC, juliusvl commented on revisions/N0/src/text/dialog_2.asm
>      db "... ... ... ... "
gadd ikke endre fra originalen, tenker det blir fint sånn?

2022-10-21 22:22 UTC, juliusvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "  DRØMMER TAR   "
ja, jeg sleit litt her, men dumt å skrive alt for langt og? veit ikke jeg, er enig i suggestion

2022-10-21 22:30 UTC, juliusvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "BRUDNE, DU SKAL "
Ja, jeg var litt fram og tilbake her. bruker vi bør eller burde?

2022-10-22 07:39 UTC, grenasberg commented on revisions/N0/src/text/dialog_2.asm
> +    db "ikke til å holde"
"holde igjen" syns jeg høres litt mer norsk ut om vi skal beholde akkurat samme ordlyd. men kanskje bedre å skrive litt om?

2022-10-22 19:14 UTC, grenasberg commented on revisions/N0/src/text/dialog_2.asm
> +    db "BRUDNE, DU SKAL "
jeg stemmer for BØR

2022-10-22 19:33 UTC, grenasberg commented on revisions/N0/src/text/dialog_2.asm
> +    db "ikke til å holde"
"Jeg kommer ikke til å spare på noe"?

2022-11-07 23:09 UTC, juliusvl commented
Oppdatert 8. november

2022-11-29 09:59 UTC, tobiasvl approved these changes

2022-11-29 09:59 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
> +    db "to templer, det "
```suggestion
    db "to templer; det "
```

2022-11-29 09:59 UTC, tobiasvl commented on revisions/N0/src/text/dialog_2.asm
>      db "... ... ... ... "
jepp enig

2023-01-12 15:40 UTC, merged