Juliusvl oversettelse dialog dx.asm
koholition/zelda-links-awakening-NO pull request #15
Opened 2022-10-23 14:14 UTC by juliusvl

2022-10-23 15:11 UTC, tobiasvl requested changes

2022-10-23 15:11 UTC, tobiasvl commented on revisions/N0/src/text/dialog_dx.asm
> +    db "Inn.            "
```suggestion
    db "inn.            "
```

2022-10-23 15:11 UTC, tobiasvl commented on revisions/N0/src/text/dialog_dx.asm
> +    db "Den som er      "
Slå sammen med linja over?

2022-10-23 15:11 UTC, tobiasvl commented on revisions/N0/src/text/dialog_dx.asm
> +;    db "Gå til stedet   "
Her kommenterte du ut oversettelsen

2022-10-23 15:11 UTC, tobiasvl commented on revisions/N0/src/text/dialog_dx.asm
> +    db "med buen."
Du har glemt @! Foreslår også "pil og bue"

```suggestion
    db "med pil og bue!@"
```

2022-10-23 19:48 UTC, tobiasvl commented on revisions/N0/src/text/dialog_dx.asm
> +    db "opp og gå hjem!@"
Skal vi være litt mer edgy som på japansk?
![image](https://user-images.githubusercontent.com/80824/197414723-7ffa3c0f-0448-4267-a0a7-f474daaebde3.png)

2022-11-07 20:20 UTC, juliusvl commented on revisions/N0/src/text/dialog_dx.asm
> +    db "Den som er      "
Slette den tomme linja, tenker du? Eller hva?

2022-11-07 20:22 UTC, juliusvl commented on revisions/N0/src/text/dialog_dx.asm
> +    db "opp og gå hjem!@"
Kan vi godt! Forslag?

2022-11-07 20:22 UTC, juliusvl commented on revisions/N0/src/text/dialog_dx.asm
> +;    db "Gå til stedet   "
hehe

2022-11-29 19:34 UTC, tobiasvl requested changes

2022-11-29 19:34 UTC, tobiasvl commented on revisions/N0/src/text/dialog_dx.asm
> +    db "ny sti!         "
```suggestion
    db "ny sti! Den som "
    db "er verdig får   "
```

2022-11-29 19:34 UTC, tobiasvl commented on revisions/N0/src/text/dialog_dx.asm
> +    db "Den som er      "
```suggestion
```

2022-11-29 19:34 UTC, tobiasvl commented on revisions/N0/src/text/dialog_dx.asm
> +    db "verdig skal få  "
```suggestion
```

2022-11-29 19:34 UTC, tobiasvl commented on revisions/N0/src/text/dialog_dx.asm
> +    db "deg kraft?! En  "
```suggestion
    db "deg kraft?! Du  "
    db "skal få råtne   "
    db "under denne     "
    db "graven!@"
```

2022-11-29 19:34 UTC, tobiasvl commented on revisions/N0/src/text/dialog_dx.asm
> +    db "tulling som deg "
```suggestion
```

2022-11-29 19:34 UTC, tobiasvl commented on revisions/N0/src/text/dialog_dx.asm
> +    db "kan like godt gi"
```suggestion
```

2022-11-29 19:34 UTC, tobiasvl commented on revisions/N0/src/text/dialog_dx.asm
> +    db "opp og gå hjem!@"
```suggestion
```

2023-03-25 15:49 UTC, tobiasvl approved these changes

2023-03-25 15:49 UTC, merged