Julius dialog
koholition/zelda-links-awakening-NO pull request #34
Opened 2023-07-19 23:33 UTC by juliusvl

2023-07-20 00:01 UTC, tobiasvl requested changes

2023-07-20 00:01 UTC, tobiasvl commented on revisions/N0/src/text/dialog_1.asm
> +    db "Ett spill 10 Rs."
"Rs." er vel forkortelse for "Rupees", funker ikke like bra for "rupier" kanskje? Hva med bare "R."? Eller "Rr." ...

2023-07-20 00:01 UTC, tobiasvl commented on revisions/N0/src/text/dialog_1.asm
> +    db "    Spill Nei<ask>"
"Spill" er for langt. Se #26

2023-07-20 00:01 UTC, tobiasvl commented on revisions/N0/src/text/dialog_1.asm
> +    db "siste!@"
Skal vi oppdatere denne sånn som Switch-versjonen gjorde?
![image](https://github.com/tobiasvl/zelda-links-awakening-NO/assets/80824/b817fc7f-d106-4d9c-9230-91d5c0757685)

2023-07-20 00:01 UTC, tobiasvl commented on revisions/N0/src/text/dialog_1.asm
> +    db "10 ripier_…     "
```suggestion
    db "10 rupier_…     "
```

2023-07-20 00:01 UTC, tobiasvl commented on revisions/N0/src/text/dialog_1.asm
> +    db "kjapt på knappen"
Kommer kanskje ikke helt klart fram at det er A eller B som menes her, men det gjør det vel ikke helt på engelsk heller, selv om der står det "Button" med stor B

2023-07-20 00:01 UTC, tobiasvl commented on revisions/N0/src/text/dialog_1.asm
> -    db "Burn, baby burn!@"
Dette er en referanse til låta Ash - Burn Baby Burn. Har vi noen lignende kulturelle referanser på norsk?

2023-07-20 00:01 UTC, tobiasvl commented on revisions/N0/src/text/dialog_4.asm
> +    db "skogen@"
```suggestion
    db "  skogen@"
```
for å justere teksten så den passer vertikalt med pilene

2023-07-20 00:01 UTC, tobiasvl commented on revisions/N0/src/text/dialog_4.asm
> +    db "På sprekker i   "
```suggestion
    db "på sprekker i   "
```

2023-07-20 00:01 UTC, tobiasvl commented on revisions/N0/src/text/dialog_4.asm
> +    db "Det går an, like"
```suggestion
    db "Det går an, ved "
```

2023-07-20 00:01 UTC, tobiasvl commented on revisions/N0/src/text/dialog_4.asm
> +;    db "På stranda_…    "
Her har du kommentert ut den norske i stedet for den engelske

2023-07-20 00:01 UTC, tobiasvl commented on revisions/N0/src/text/dialog_4.asm
> +    db "_…Tarin sier at "
```suggestion
    db "_… Tarin sier at"
```

2023-07-20 00:01 UTC, tobiasvl commented on revisions/N0/src/text/dialog_4.asm
> +    db "Det spiller     "
Her oppdaterte de den engelske teksten litt på Switch så det høres mer naturlig ut, skal vi også gjøre det?
![image](https://github.com/tobiasvl/zelda-links-awakening-NO/assets/80824/54189470-18dd-4525-89b4-68b9fe9520af)

2023-07-20 00:01 UTC, tobiasvl commented on revisions/N0/src/text/dialog_4.asm
> +; Foreslår å la denne stå mvh Julius
Da gjør vi sånn her så hvormye teller riktig
```suggestion
    db "ZZZ ZZZ ZZZ ZZZ "
    db " ... <marin> ... <marin> ...@"
```

2023-07-20 00:01 UTC, tobiasvl commented on revisions/N0/src/text/dialog_4.asm
> +    db "havfruen. Hvor-
```suggestion
    db "havfruen. Hvor- "
```

2023-07-20 00:01 UTC, tobiasvl commented
@grenasberg Her har Julius oversatt samme fil som deg, vil du se over og se om det er mye konflikt?

2023-07-20 07:12 UTC, juliusvl commented on revisions/N0/src/text/dialog_1.asm
> +    db "Ett spill 10 Rs."
eller kanskje Ru.? Eller funker det bedre å forkorte med konsonant enn vokal, kanskje?

2023-07-20 21:50 UTC, grenasberg commented on revisions/N0/src/text/dialog_1.asm
> +    db "Ett spill 10 Rs."
eller Rp? rp rp rp

Neida. Heller mest mot R jeg. som sør-afrikansk Rand, eller Riksdaler. Eller skal vi legge inn ₹ - Rupee?

2023-07-20 21:53 UTC, grenasberg commented on revisions/N0/src/text/dialog_1.asm
> +    db "    Spill Nei<ask>"
```suggestion
    db "    Prøv Niks<ask>"
```
hva med dette i stedet?

2023-07-20 21:56 UTC, grenasberg commented on revisions/N0/src/text/dialog_1.asm
> +    db "siste!@"
er ikke det en mer anniversary-feature? skal ikke vårt spill være en oversettelse av det som var? det er et veivalg selvsagt. har vi gjort noen grep tidligere som går utenfor manuset? vi har klartgjort enkelte greier som var litt dårlig forklart.

2023-07-20 22:14 UTC, grenasberg commented on revisions/N0/src/text/dialog_1.asm
> -    db "Burn, baby burn!@"
er det ikke referanse til Disco Inferno? https://legendsoflocalization.com/you-got-disco-in-my-zelda/

hva med: 
Håper ikke Hans Olav Brenner vil savne den
Byen e bergen og laget er BRANN!
Du føler allerede en brennende kjærlighet for dette våpenet! (ikke en referanse)
Hus/hotell/slott brenner
Noen må ringe Bjørnis!

2023-07-20 22:15 UTC, grenasberg commented on revisions/N0/src/text/dialog_1.asm
> +    db "Du fikk Rokkens "
Jeg heller nok mot Rokks fjær i stedet. Rokkens fjær blir liksom. en Rokk som man spinner med, du vet, som i Tornerose

2023-07-20 22:19 UTC, grenasberg commented on revisions/N0/src/text/dialog_4.asm
>      db "    Yes  No<ask>"
```suggestion
    db "    Ja   Nei<ask>"
```
Glemte du å oversette dette?

2023-07-20 22:22 UTC, grenasberg commented on revisions/N0/src/text/dialog_4.asm
> +    db "deg_… Eeh_… Eh_…"
```suggestion
    db "deg_… Eeh_… Øh_…"
```

2023-07-21 13:02 UTC, juliusvl commented on revisions/N0/src/text/dialog_1.asm
> +    db "Ett spill 10 Rs."
I så fall trur jeg ikke det blir noe særlig penere enn dette:
<img width="125" alt="image" src="https://github.com/tobiasvl/zelda-links-awakening-NO/assets/16557480/5391df97-78de-4442-a6a3-084aab2e2a4e">

2023-07-21 14:33 UTC, juliusvl commented on revisions/N0/src/text/dialog_1.asm
> +    db "Du fikk Rokkens "
Ja, litt enig. Kanskje Rokks er best?

2023-07-21 14:34 UTC, juliusvl commented on revisions/N0/src/text/dialog_4.asm
> +;    db "På stranda_…    "
Fikser jeg det ved å bare redigere i fila i riktig branch?

2023-07-21 14:36 UTC, juliusvl commented on revisions/N0/src/text/dialog_1.asm
> +    db "kjapt på knappen"
Ja, kanskje gjøre det mer tydelig. Man kan bruke både A og B, jeg sjekka

2023-07-22 19:41 UTC, grenasberg commented on revisions/N0/src/text/dialog_1.asm
> +    db "Du fikk Rokkens "
```suggestion
    db "Du fikk Rokks   "
```

2023-07-23 12:27 UTC, grenasberg commented on revisions/N0/src/text/dialog_1.asm
> +    db "Ett spill 10 Rs."
nei vi går for R

2023-07-25 21:04 UTC, grenasberg commented on revisions/N0/src/text/dialog_1.asm
> +    db "Ett spill 10 Rs."
```suggestion
    db "Ett spill 10 R. "
```

2023-08-16 13:12 UTC, juliusvl commented on revisions/N0/src/text/dialog_1.asm
> +    db "Ett spill 10 Rs."
Kan prøve å lage en bedre ₹ i kveld, så kan vi vurdere.

2023-08-16 13:13 UTC, juliusvl commented on revisions/N0/src/text/dialog_1.asm
> +    db "siste!@"
Litt enig med Andreas her, gøyere med ganske rein oversettelse. Passer jo ikke helt med Kukeman-dialogene våre da, hehe

2023-08-17 11:09 UTC, grenasberg commented on revisions/N0/src/text/dialog_1.asm
> +    db "siste!@"
cukeman-dialogen skal være easter-eggs/tull fra utviklerne/oversetterne, så den er innafor imo

2023-08-17 11:10 UTC, grenasberg commented on revisions/N0/src/text/dialog_4.asm
> +;    db "På stranda_…    "
redigere og committe

2023-08-17 14:59 UTC, grenasberg commented on revisions/N0/src/text/dialog_4.asm
> +;    db "På stranda_…    "
fikset i min branch nu

2023-08-17 15:02 UTC, grenasberg commented on revisions/N0/src/text/dialog_4.asm
> +    db "Det spiller     "
ja

2023-08-17 15:29 UTC, tobiasvl approved these changes

2023-08-17 15:29 UTC, merged